[package]
name = "duckdb_minijinja_binding"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "duckdb_minijinja_binding"
crate-type = ["staticlib"]

[dependencies]
minijinja = { version = "2.12.0", features = ["deserialization", "loader"] }
serde_json = "1.0.145"
